## An array is a special variable, which can hold more than one value at a time. In Python, array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together.
An array can hold many values under a single name, and you can access the values by referring to an index number.



 NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

## Most NumPy arrays have some restrictions. For instance:

>>> All elements of the## array must be of the same type of data.

>>> Once created, the total size of the array can’t change.

>>> The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - ---------------


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

print(np.__version__)

2.2.4


In [ ]:
import numpy as np
import time

# Create a large list and a NumPy array
size = 10  # 1 million elements
py_list = list(range(size))
np_array = np.array(py_list)

#  Addition using Python list
start = time.time()
py_list_result = [x + 5 for x in py_list]  # List comprehension
end = time.time()
print(f"Python List Time: {end - start:.5f} seconds")

#  Addition using NumPy array
start = time.time()
np_array_result = np_array + 5  # Vectorized operation
end = time.time()
print(f"NumPy Array Time: {end - start:.5f} seconds")

#  Memory usage
print(f"Python List Memory: {py_list.__sizeof__()} bytes")
print(f"NumPy Array Memory: {np_array.nbytes} bytes")
py_list_result

Python List Time: 0.00000 seconds
NumPy Array Time: 0.00100 seconds
Python List Memory: 120 bytes
NumPy Array Memory: 40 bytes


[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
# 0d array
a0=np.array(45 ) # create a 0d array
print(a0)
print(type(a0))


45
<class 'numpy.ndarray'>


In [ ]:
a1=np.array(
    [1,2,3,4,5], # 1d array
    dtype=np.int32 # specify the data type

           )
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a2 = np.array([[1, 2, 3, 4],
               [5, 6, 4, 8],
               [9, 10, 11, 12]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.ndim)


[[ 1  2  3  4]
 [ 5  6  4  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
(3, 4)
2


In [ ]:

a3= np.array([[[1, 2, 3],
                [4, 5, 6]],
                  [[1, 2, 3],
                    [4, 5, 6]]])

print(a3)
print(type(a3))
print(a3.shape)
print(a3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3


In [ ]:
ah=np.array([1,2,3,4,5],dtype=np.int32,ndmin=5)
print(ah)
print(type(ah))
print(ah.shape)
print(ah.ndim)

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>
(1, 1, 1, 1, 5)
5


## Array attributes

>>> This section covers the

>>> ndim, shape, size, and dtype

attributes of an array.

This section covers ndarray.ndim, ndarray.size, ndarray.shape

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(array_example.size)
print(array_example.shape)
array_example.ndim

# 3 blocks (depth)

# 2 rows per block

# 4 columns per row

24
(3, 2, 4)


3

## How to create a basic array

This section covers
>>>  np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()



In [ ]:
zero=np.zeros(10)
print(zero)
zero=np.zeros((3, 4)) # create a 3x4 array of zeros
print(zero)

range_array = np.arange(10) # create an array of numbers from 0 to 9
print(range_array)

range_array_with_step = np.arange(0, 10, 2) # create an array of numbers from 0 to 9 with step of 2
print(range_array_with_step)

range_array_with_linspace=np.linspace(0, 1, 5) # create an array of 5 numbers between 0 and 1

print(range_array_with_linspace)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## ndexing/slicing /acces elements

In [2]:
print(a1)

# from simple array


print(a1[0]) # first element
print(a1[1]) # second element
print(a1[2]) # third element
print(a1[3]) # fourth element
print(a1[-1]) # last element
print(a1[-2]) # second last element

# first three elements
print(a1[1:4]) # second to fourth elements
print(a1[1:]) # from second to last element
print(a1[:4]) # first four elements
print(a1[:]) # all elements

print(a1[::2]) # every second element
print(a1[::-1]) # reverse the array
print(a1[1:4:2]) # second to fourth elements with step of 2


NameError: name 'a1' is not defined

## Access 2-D Arrays


In [ ]:
print(a2)
print(np.shape(a2)) # shape of the array
print(a2[0, 0]) # first row, first column
print(a2[0, 1]) # first row, second column
print(a2[1, 0]) # second row, first column
print(a2[1, 1]) # second row, second column
print(a2[0, :]) # first row
print(a2[:, 0]) # first column
print(a2[0, 0:2]) # first row, first two columns
print(a2[0:2, 0:2]) # first two rows, first two columns
print(a2[0:2, :]) # first two rows, all columns
print(a2[:, 0:2]) # all rows, first two columns
print(a2[0:2, 0:2]) # first two rows, first two columns

# to do Try -Ve

[[ 1  2  3  4]
 [ 5  6  4  8]
 [ 9 10 11 12]]
(3, 4)
1
2
5
6
[1 2 3 4]
[1 5 9]
[1 2]
[[1 2]
 [5 6]]
[[1 2 3 4]
 [5 6 4 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[1 2]
 [5 6]]


## Access 3-D Arrays


In [ ]:
print(a3)
print(a3[0, 0, 0]) # first block, first row, first column
print(a3[0, 0, 1]) # first block, first row, second column
print(a3[0, 1, 0]) # first block, second row, first column
print(a3[0, 1, 1]) # first block, second row, second column
print(a3[1, 0, 0]) # second block, first row, first column
print(a3[1, 0, 1]) # second block, first row, second column

print(a3[1, 1, 0]) # second block, second row, first column



[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
4
5
1
2
4


## Negative Indexing
To do create all these array and apply -ve indexing  to acces elements

In [ ]:
print(a1)  # 1d array slicing
print(a1[0:3])
print(a1[1:4])
print(a1[1:])
print(a1[:4])
print(a1[:])
print(a1[::2])
print(a1[::-1])
print(a1[1:4:2]) # second to fourth elements with step of 2


[1 2 3 4 5]
[1 2 3]
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]
[2 4]


In [ ]:
print(a3) # 3d array slicing
print(a3[0, 0, 0]) # first block, first row, first column
print(a3[0, 0, 1]) # first block, first row, second column
print(a3[0, 1, 0]) # first block, second row, first column
print(a3[0, 1, 1]) # first block, second row, second column
print(a3[1, 0, 0]) # second block, first row, first column
print(a3[1, 0, 1]) # second block, first row, second column
print(a3[1, 1, 0]) # second block, second row, first column
print(a3[1, 1, 1]) # second block, second row, second column
print(a3[0, 0, :]) # first block, first row, all columns
print(a3[0, :, 0]) # first block, all rows, first column
print(a3[:, 0, 0]) # all blocks, first row, first column
print(a3[:, 0, :]) # all blocks, first row, all columns
print(a3[:, :, 0]) # all blocks, all rows, first column
print(a3[:, :, 1]) # all blocks, all rows, second column
print(a3[:, :, :]) # all blocks, all rows, all columns
print(a3[0:2, 0:2, 0:2]) # first two blocks, first two rows, first two columns
print(a3[0:2, 0:2, :]) # first two blocks, first two rows, all columns

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
4
5
1
2
4
5
[1 2 3]
[1 4]
[1 1]
[[1 2 3]
 [1 2 3]]
[[1 4]
 [1 4]]
[[2 5]
 [2 5]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


##  Copy vs View

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
print(a1)
x=a1.copy() # create a copy of the array
print(x)
x[3]=100 # modify the copy
print(x) # check the modified copy
print(a1) # check the original array


y=a1.view() # create a view of the array
print(y)
y[3]=100 # modify the view
print(y) # check the modified view
print(a1) # check the original array

[1 2 3 4 5]
[1 2 3 4 5]
[  1   2   3 100   5]
[1 2 3 4 5]
[1 2 3 4 5]
[  1   2   3 100   5]
[  1   2   3 100   5]


## Reshaping arrays


In [ ]:
print(a1)
print(a1.size) # size of the array
print(a1.shape) # shape of the array

print(a1.ndim) # number of dimensions of the array

print(a1.reshape(5, 1)) # reshape the array to 5 rows and 1 column

[  1   2   3 100   5]
5
(5,)
1
[[  1]
 [  2]
 [  3]
 [100]
 [  5]]


In [ ]:
Aprint(a2)
print(a2.size) # size of the array
print(a2.shape) # shape of the array
print(a2.ndim) # number of dimensions of the array

print(a2.reshape(3, 4)) # reshape the array to 3 rows and 4 columns
print(a2.reshape(4, 3)) # reshape the array to 4 rows and 3 columns

[[ 1  2  3  4]
 [ 5  6  4  8]
 [ 9 10 11 12]]
12
(3, 4)
2
[[ 1  2  3  4]
 [ 5  6  4  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 4  8  9]
 [10 11 12]]


In [ ]:
print(a3)
print(a3.size) # size of the array
print(a3.shape) # shape of the array
print(a3.ndim) # number of dimensions of the array
print(a3.reshape(2, 3, 2)) # reshape the array to 2 blocks, 3 rows and 2 columns
print(a3.reshape(3, 2, 2)) # reshape the array to 3 blocks, 2 rows and 2 columns

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
12
(2, 2, 3)
3
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [1 2]]

 [[3 4]
  [5 6]]]


### to do take multiple block in 2,3d array and reshape them

## 1D NumPy array to a 2D NumPy array

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

print(a1.reshape(5, 1)) # reshape the array to 5 rows and 1 column

print(a1.reshape(1, 5)) # reshape the array to 1 row and 5 columns


[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


In [ ]:
print(a1[np.newaxis,: ]) # reshape the array to 5 rows, 1 column and 1 depth

[[1 2 3 4 5]]


In [ ]:
print(a1[:,np.newaxis ]) # reshape the array to 5 rows, 1 column and 1 depth
a1

[[1]
 [2]
 [3]
 [4]
 [5]]


array([1, 2, 3, 4, 5])

In [ ]:
print(np.expand_dims(a1, axis=0)) # expand the dimensions of the array to 5 rows, 1 column and 1 depth
print(np.expand_dims(a1, axis=1)) # expand the dimensions of the array to 5 rows, 1 column and 1 depth


[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
## np.vstack(), np.hstack(), np.hsplit(),

## np.vsplit(), np.concatenate(), np.r_[], np.c_[]
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:

print(np.vstack((a, b))) # vertical stack
print(np.hstack((a, b))) # horizontal stack

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:

print(np.hsplit(a, 3)) # horizontal split
print(np.vsplit(a, 2)) # vertical split

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
print(a-b) # element wise subtraction
print(a+b) # element wise addition
print(a*b) # element wise multiplication
print(a/b) # element wise division
 print(a**2) # element wise power



[[-6 -6 -6]
 [-6 -6 -6]]
[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
(a.mean()) # mean of the array
print(a.sum()) # sum of the array
print(a.max()) # maximum of the array
print(a.min()) # minimum of the array
print(a.std()) # standard deviation of the array
print(a.var()) # variance of the array


3.5
21
6
1
1.707825127659933
2.9166666666666665


In [ ]:
print(a.shape) # shape of the array
print(b.shape) # shape of the array
print(a.ndim)
print(b.ndim) # number of dimensions of the array

#need same number of columns for dot product
print(a.T) # transpose of the array

print(np.dot(a, b.T)) # dot product of the array

(2, 3)
(2, 3)
2
2
[[1 4]
 [2 5]
 [3 6]]
[[ 50  68]
 [122 167]]


## Broadcasting

In [ ]:
A = np.array([[1, 2], [3, 4]])  # Shape (2,2)
B = np.array([10, 20, 30, 40])  # Shape (4,) - Must be reshaped

# Reshape B to (2,2) so it matches A
B_reshaped = B.reshape(2,2)

result = A + B_reshaped
print(result)


[[11 22]
 [33 44]]


In [ ]:
print(np.unique(a)) # unique elements of the array
print(np.unique(a, return_index=True)) # unique elements of the array with index
print(np.unique(a, return_inverse=True)) # unique elements of the array with inverse index
print(np.unique(a, return_counts=True)) # unique elements of the array with counts
print(np.unique(a, return_counts=True, axis=0)) # unique elements of the array with counts and axis
print(np.unique(a, return_counts=True, axis=1)) # unique elements of the array with counts and axis



[1 2 3 4 5 6]
(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64))
(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64))
(array([1, 2, 3, 4, 5, 6]), array([1, 1, 1, 1, 1, 1], dtype=int64))
(array([[1, 2, 3],
       [4, 5, 6]]), array([1, 1], dtype=int64))
(array([[1, 2, 3],
       [4, 5, 6]]), array([1, 1, 1], dtype=int64))


In [ ]:
#np.flip()
print(a)
print(np.flip(a)) # flip the array
print(np.flip(a, axis=0)) # flip the array along axis 0
print(np.flip(a, axis=1)) # flip the array along axis 1

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [ ]:
## .flatten(), ravel()   reshape nulti dimensional array to 1d array

print(a.flatten()) # flatten the array
print(a.ravel()) # flatten the array


# ravel is view and flatten is copy




[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
